/**
 * 서버 오류 응답 `code`. 화면은 HTTP 숫자가 아니라 이 값으로 문구를 분기한다.
 * 원천: 백엔드 `common/exception/ErrorCode.kt` (develop @ f719493, 2026-09-01).
 * 서버는 enum 이름을 그대로 code로 내보낸다 — 키와 값이 항상 같다.
 */
export const ERROR_CODES = {
  // 400
  INVALID_INPUT: "INVALID_INPUT",
  UNSUPPORTED_PROVIDER: "UNSUPPORTED_PROVIDER",
  UNSUPPORTED_ROOM_TYPE: "UNSUPPORTED_ROOM_TYPE",
  INVALID_QUESTION: "INVALID_QUESTION",
  // 401 — 만료는 항상 401이어야 client.ts의 refresh가 발화한다
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  SOCIAL_TOKEN_INVALID: "SOCIAL_TOKEN_INVALID",
  // 402
  INSUFFICIENT_COINS: "INSUFFICIENT_COINS",
  // 403
  ACCESS_DENIED: "ACCESS_DENIED",
  NOT_ROOM_HOST: "NOT_ROOM_HOST",
  NOT_QUESTION_SET_OWNER: "NOT_QUESTION_SET_OWNER",
  HOST_LEVEL_REQUIRED: "HOST_LEVEL_REQUIRED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  GUEST_NOT_ALLOWED: "GUEST_NOT_ALLOWED",
  // 404
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  QUESTION_SET_NOT_FOUND: "QUESTION_SET_NOT_FOUND",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  PARTICIPANT_NOT_FOUND: "PARTICIPANT_NOT_FOUND",
  // 409
  CONFLICT: "CONFLICT",
  ROOM_NOT_JOINABLE: "ROOM_NOT_JOINABLE",
  ROOM_FULL: "ROOM_FULL",
  NICKNAME_DUPLICATED: "NICKNAME_DUPLICATED",
  ALREADY_JOINED: "ALREADY_JOINED",
  QUESTION_SET_ALREADY_CONFIRMED: "QUESTION_SET_ALREADY_CONFIRMED",
  QUESTION_SET_EMPTY: "QUESTION_SET_EMPTY",
  // 500 / 502
  PIN_GENERATION_FAILED: "PIN_GENERATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  AI_GENERATION_FAILED: "AI_GENERATION_FAILED",
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",

  /** @draft 서버 enum에 아직 없다 — 별점 기능(우선순위 3) 미구현. 구현 시 서버가 추가한다 */
  ALREADY_RATED: "ALREADY_RATED",
  /** @draft 서버 enum에 아직 없다 — 게스트 기록 전환(우선순위 3) 미구현 */
  RECORD_PURGED: "RECORD_PURGED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
